// Supabase configuration
const SUPABASE_URL = 'https://istmrrnszmtrfkxzuhpi.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdG1ycm5zem10cmZreHp1aHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTkyMzgsImV4cCI6MjA1NTkzNTIzOH0.GF5YJ2r_P2S1WJ2cTTaigYAkfDLriz7Lv354bNIx7Hw';
